micronaut:
  application:
    name: museumssonntag

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'password123'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update

museumssonntag:
  bot: "1234567890:RANDOMHASHGIVENBYTELEGRAM"
  users: "123456789:Aydar,987654321:Sveta"
